# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='Event Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Event End Date')),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=10000)),
                ('ticket_cost', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-start_date',),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=100)),
                ('prize', models.ManyToManyField(to='lan.Prize')),
            ],
        ),
    ]
