# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lan.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='Event Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Event End Date')),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('ticket_cost', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-start_date',),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_homepage', models.BooleanField(help_text='Click here if you want this page to be the current home page')),
                ('homepage_name', models.CharField(max_length=35)),
                ('heading', models.CharField(default='Central New York LAN', help_text='The main heading for the homepage', max_length=200)),
                ('subheading', models.CharField(default='Default subheading', help_text='The subheading just below the heading', max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, height_field='height_field', null=True, upload_to=lan.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('left_content_heading', models.CharField(default='Default Left Heading Title', help_text='A heading for left side page content. Not currently Implemented', max_length=200)),
                ('right_content_heading', models.CharField(default='Default Right Heading Title', help_text='A heading for right side page content. Not currently Implemented', max_length=200)),
                ('featured_event', models.ForeignKey(blank=True, help_text='If selected item from this event will be featured on the home page.', null=True, on_delete=django.db.models.deletion.CASCADE, to='lan.Event')),
                ('featured_games', models.ManyToManyField(blank=True, help_text='Games to show on the homepage.', to='lan.Game')),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prize', models.ManyToManyField(to='lan.Prize')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='lan.Sponsor'),
        ),
    ]
