# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Central New York LAN', help_text='The main heading for the homepage', max_length=200)),
                ('subheading', models.CharField(default='Next LAN', help_text='The subheading just below the heading', max_length=200)),
                ('left_content_heading', models.CharField(default='Sponsors and Prizes', max_length=200)),
                ('right_content_heading', models.CharField(default='Games Played', max_length=200)),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_event',
            field=models.ForeignKey(blank=True, help_text='If selected item from this event will be featured on the home page.', null=True, on_delete=django.db.models.deletion.CASCADE, to='lan.Event'),
        ),
        migrations.AddField(
            model_name='game',
            name='homepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lan.HomePage'),
        ),
    ]
