# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import lan.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='middle_content_heading',
            field=models.CharField(default='Default Left Heading Title', help_text='A heading for left side page content', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='lan.Sponsor'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='height_field', help_text="This is where you would select an image for a banner or jumbotron.                    I haven't built this into the Html so it wouldn't show up anywhere right now.", null=True, upload_to=lan.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='left_content_heading',
            field=models.CharField(default='Default Middle Heading Title', help_text='A heading for left side page content', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='right_content_heading',
            field=models.CharField(default='Default Right Heading Title', help_text='A heading for left side page content', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='prize',
            field=models.ManyToManyField(blank=True, to='lan.Prize'),
        ),
    ]
