# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0002_auto_20160515_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='homepage',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_games',
            field=models.ManyToManyField(blank=True, help_text='Games to show on the homepage.', null=True, to='lan.Game'),
        ),
    ]
