# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lan.models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0002_auto_20160521_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', help_text="This is where you would select an image for a banner or jumbotron.                                    I haven't built this into the Html so it wouldn't show up anywhere right now.", null=True, upload_to=lan.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='left_content_heading',
            new_name='first_content_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='middle_content_heading',
            new_name='second_content_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='right_content_heading',
            new_name='third_content_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='width_field',
        ),
        migrations.AddField(
            model_name='images',
            name='homepage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lan.HomePage'),
        ),
    ]
