# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0003_auto_20160515_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_games',
            field=models.ManyToManyField(blank=True, help_text='Games to show on the homepage.', to='lan.Game'),
        ),
    ]
