# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0004_auto_20160521_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='label',
            field=models.CharField(default='header', max_length=50),
            preserve_default=False,
        ),
    ]
