# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0004_auto_20160515_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_name',
            field=models.CharField(default='first', max_length=25),
            preserve_default=False,
        ),
    ]
