# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0005_homepage_homepage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='current_homepage',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
