# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0006_homepage_current_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='lan.Sponsor'),
        ),
    ]
