# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0010_auto_20160517_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='homepage_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='left_content_heading',
            field=models.CharField(default='Default Left Heading Title', help_text='A heading for left side page content. Not currently Implemented', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='right_content_heading',
            field=models.CharField(default='Default Right Heading Title', help_text='A heading for right side page content. Not currently Implemented', max_length=200),
        ),
    ]
