# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import lan.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0012_auto_20160517_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='height_field', null=True, upload_to=lan.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
